.gitlab-ci.yml
Auto compile on gitlab (if I create this file on gitlab, the repository can't be mirrored)
=> Added .gitlab-ci.yml for Auto Compile on gitlab

escher/src/text_area.cpp, ion/include/ion/events.h, ion/include/ion/keyboard/layout_B2/layout_events.h, ion/include/ion/keyboard/layout_B3/layout_events.h
=> Shift+Up and Shift+Down in python editor (closes #177)

ion/include/ion/keyboard/layout_B2/layout_events.h, ion/include/ion/keyboard/layout_B3/layout_events.h
https://github.com/Omega-Numworks/Omega/issues/205
=> Fixed #205

Makefile, apps/external/extapp_api.cpp
Fix with upstream new makefile var names
=> [Fix] Compilation crash (Makefile + External)

escher/image/inliner.c
=> [Feature] RGB files compatibility

ion/include/ion/keyboard/layout_B2/layout_events.h, ion/include/ion/keyboard/layout_B3/layout_events.h
Add backslash and at on the keyboard as requested on #348. It's ready to be merged :smile:
=> [Feature] Add \ and @ 

apps/calculation/additional_outputs/complex_graph_cell.cpp, apps/calculation/additional_outputs/expression_with_equal_sign_view.h, apps/calculation/additional_outputs/illustration_cell.cpp, apps/calculation/additional_outputs/scrollable_three_expressions_cell.h, apps/calculation/additional_outputs/trigonometry_graph_cell.cpp, apps/code/console_line_cell.cpp, apps/code/editor_view.cpp, apps/code/script_parameter_controller.cpp, apps/hardware_test/keyboard_view.cpp, apps/probability/distribution_controller.h, apps/shared/curve_view.cpp, apps/shared/scrollable_multiple_expressions_view.cpp, apps/variable_box_empty_controller.cpp, escher/include/escher/scrollable_expression_view.h, escher/src/palette.cpp
Based on #261 and https://github.com/Omega-Numworks/Omega/pull/261#pullrequestreview-361320446
=> [Fix] Patched colors

.github/workflows/ci-docker.yml, docker/Dockerfile, docker/build, docker/readme.md
=> [Docker] Add docker and docker CI

.github/workflows/ci-workflow.yml
This is needed because of the lack of space.
=> N0100 Generate one binary per langage

poincare/include/poincare/unit.h
steradian, lux and lumen were fixed
The freedom units worked well :shrug:
=> [Fix] Fixed Units to work with the new 

apps/code/script_template.cpp, ion/include/ion/storage.h, ion/src/shared/storage.cpp, python/Makefile, python/port/genhdr/qstrdefs.in.h, python/port/mod/ion/file.cpp, python/port/mod/os/modos.cpp, python/port/mod/os/modos.h, python/port/mod/os/modos_table.c, python/port/mod/os/uname_result.cpp, python/port/mpconfigport.h
=> [mpy] Fix crash on append on new file, new os module

apps/home/controller.cpp, escher/include/escher/selectable_table_view.h, escher/src/selectable_table_view.cpp
This fix https://github.com/Omega-Numworks/Omega/issues/85
=> [Apps/home] Change menu behaviour with incomplete lines

ion/src/device/shared/usb/calculator.h
=> [Ion/usb] Changed URL in order to have easier update

build/targets.device.n0110.mak
=> [build] Remove bash-ismes

README.fr.md, README.md
Added README.fr.md to the dev branch and linked README files together so people who read one of them and don't understand its content can quickly and simply jump to the other one.
=> [readme] Added French README

apps/external/archive.cpp
This fixes :
- The size of the first file being 0
- The size of the other files being files being shifted which fixes the external icons rendering issues
- Not having access to an app in exam mode if a normal file is before it
=> [external] Fixed #492

apps/settings/sub_menu/about_controller.cpp, apps/settings/sub_menu/generic_sub_controller.h, apps/settings/sub_menu/math_options_controller.cpp
- Fixed #151 
- Fixed AboutController not working properly when no username is present.
=> Fixed issues with settings

apps/shared/localization_controller.cpp, apps/shared/localization_controller.h
This fixes https://github.com/Omega-Numworks/Omega/issues/534
=> [shared/localization] Fix theme palette

bootloader/boot.cpp, bootloader/interface.cpp, bootloader/interface.h, bootloader/slot.cpp, bootloader/slot.h, bootloader/slot_exam_mode.cpp, bootloader/slot_exam_mode.h, bootloader/userland_header.cpp
Fix Exam on E16 and E19+
Fix E20 and E16 in bootloader menu
Erase bootloader update if exist in E20 Slot
Better bootloader menu
=> E20 and QOL

ion/src/shared/dummy/usb.cpp, ion/src/simulator/3ds/driver/usb.cpp
Fixes
```
/home/heath/omega-cleanbuild/OmegaVanilla/apps/apps_container.cpp:154: undefined reference to `Ion::USB::DFU(bool, int)'
```
=>  Fix simulator
